service: Otto-SetupUserProvisions

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  profile: ${opt:stage}
  timeout: 60
  memorySize: 128
  environment:
    RDS_HOSTNAME: ${file(./serverless.env.yml):${opt:stage}.RDS_HOSTNAME}
    RDS_USERNAME: ${file(./serverless.env.yml):${opt:stage}.RDS_USERNAME}
    RDS_PASSWORD: ${file(./serverless.env.yml):${opt:stage}.RDS_PASSWORD}
    RDS_PORT: ${file(./serverless.env.yml):${opt:stage}.RDS_PORT}
    RDS_DATABASE: ${file(./serverless.env.yml):${opt:stage}.RDS_DATABASE}
    secret: ${file(./serverless.env.yml):${opt:stage}.secret}
    monthsToCount: 3
    minPeriodsToCheck: 2
functions:
  setupProvisions:
    handler: src/setup/handler.setupProvisions
    events:
      - schedule:
          rate: cron(4/5 * * * ? *)
          description: 'Setup user provisions'
          enabled: true
plugins:
  - serverless-offline